const firstNames = ["Juan","Maria","Jose","Ana","Carlos","Rosa","Miguel","Clara","Luis","Sofia","Ramon","Elena","Pedro","Luz","Antonio","Carmen","Eduardo","Pilar","Ricardo","Nena","Felix","Gloria","Mario","Celia","Roberto","Lilia","Manuel","Norma","Andres","Perla","Rafael","Tessie","Ernesto","Minda","Rodolfo","Corazon","Arturo","Josephine","Dante","Marilou","Renato","Maricel","Rolando","Rosario","Domingo","Florencia","Wilfredo","Edna","Reynaldo","Cristina","Nestor","Virginia","Oscar","Angelita","Alfredo","Teresita","Leonardo","Remedios","Benjamin","Lourdes","Crisanto","Felicidad","Armando","Mercedita","Patricio","Salome","Eliseo","Adoracion","Delfin","Milagros","Leonora","Virgilio","Rosita","Marcelo","Carmelita","Eugenio","Paz","Herminio","Magdalena","Celestino","Amparo","Faustino","Leticia","Narciso","Delia","Conrado","Herminia","Hilario","Imelda","Porfirio","Erlinda","Godofredo","Perpetua","Victorino","Felisa","Ambrosio","Pacita","Bonifacio","Segundina","Esteban"];
const lastNames = ["Dela Cruz","Santos","Reyes","Garcia","Flores","Bautista","Ramos","Mendoza","Torres","Aquino","Diaz","Lopez","Navarro","Castillo","Cruz","Hernandez","Villanueva","Aguilar","Morales","Ramirez","Pascual","Salazar","Rojas","Gutierrez","Valdez","Medina","Molina","Cabrera","Guerrero","Lim","Tan","Go","Sy","Ong","Ang","Co","Dy","Yu","Chua","Chan","Soriano","Vergara","Tolentino","Ferrer","Evangelista","Macaraeg","Macapagal","Quiambao","Buenaventura","Baluyot","Mateo","Dumlao","Pangilinan","Mercado","Ocampo","Delos Reyes","Manalo","Espiritu","Velasquez","Roxas","Ilagan","Magno","Vizcarra","Tomas","Sison","Legaspi","Paredes","Galang","Coronado","Silverio","Padua","Alcantara","Perez","Miranda","Balagtas","Enriquez","Lumibao","Pineda","Sabino","Tiangco","Bartolome","Cunanan","Lacson","Belen","Calixto","Narciso","Domingo","Umali","Sevilla","Mapua","Advincula","Badillo","Calma","Dalisay","Estepa","Fajardo","Gabisan","Hadap","Intal","Jasareno"];
const mis = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","Y","Z"];
const PROGRAMS = { CS:{full:"Bachelor of Science in Computer Science",prefix:"BSCS"}, IT:{full:"Bachelor of Science in Information Technology",prefix:"BSIT"}, ACT:{full:"Bachelor of Science in Computer Technology",prefix:"BSACT"} };
function sec(program,year,i){ const l=program==="ACT"?["A"]:["A","B","C"]; return `${PROGRAMS[program].prefix}-${year}${l[i%l.length]}`; }
const cohorts=[{year:1,sem:2,program:"CS",count:40},{year:1,sem:2,program:"IT",count:40},{year:1,sem:2,program:"ACT",count:20},{year:2,sem:2,program:"CS",count:90},{year:2,sem:2,program:"IT",count:80},{year:2,sem:2,program:"ACT",count:30},{year:3,sem:2,program:"CS",count:65},{year:3,sem:2,program:"IT",count:60},{year:4,sem:2,program:"CS",count:38},{year:4,sem:2,program:"IT",count:37}];
let students=[],id=1,fi=0,li=0,mi=0;
for(const c of cohorts){ for(let i=0;i<c.count;i++){ const fn=firstNames[fi%firstNames.length],ln=lastNames[li%lastNames.length],m=mis[mi%mis.length],pid=String(id).padStart(5,"0"),p=PROGRAMS[c.program]; students.push({studentId:`2024-${pid}`,firstName:fn,lastName:ln,middleInitial:m,program:c.program,programFull:p.full,yearLevel:c.year,currentSem:c.sem,section:sec(c.program,c.year,i),email:`${fn.toLowerCase().replace(/\s/g,"")}.${ln.toLowerCase().replace(/[\s.]/g,"")}@wmsu.edu.ph`}); id++;fi++;li=(li+3)%lastNames.length;mi=(mi+7)%mis.length; } }
const out=["// ─────────────────────────────────────────────────────────────","// WMSU-Ease — Student Mock Data","// 500 students · CS / IT / ACT · Year 1–4","// Replace with a real API fetch when the backend is ready.","// ─────────────────────────────────────────────────────────────","","const STUDENT_DB = [",...students.map((s,idx)=>`  { studentId:"${s.studentId}", firstName:"${s.firstName}", lastName:"${s.lastName}", middleInitial:"${s.middleInitial}", program:"${s.program}", programFull:"${s.programFull}", yearLevel:${s.yearLevel}, currentSem:${s.currentSem}, section:"${s.section}", email:"${s.email}" }${idx<students.length-1?",":""}`),"]; ","","// ─────────────────────────────────────────────────────────────","// LOOKUP — called by re-enrollment.js → prefillFromSession()","// Returns the student object matching the given ID, or null.","// ─────────────────────────────────────────────────────────────","function findStudentById(id) {","    return STUDENT_DB.find(s => s.studentId === id) || null;","}"];
process.stdout.write(out.join("\n")+"\n");